// @vitest-environment jsdom
import 'fake-indexeddb/auto';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import type { ImageAsset } from '../src/lib/types';
vi.mock('../src/lib/firebase', () => ({ auth: undefined, db: undefined, storage: undefined, isPreview: true, configError: '' }));
vi.mock('../src/lib/gemini', () => ({ MODEL: 'gemini-3-pro-image', validateKey: vi.fn().mockResolvedValue(undefined), generateImage: vi.fn() }));
vi.mock('../src/lib/images', async importOriginal => ({ ...await importOriginal<typeof import('../src/lib/images')>(), readImage: vi.fn().mockImplementation(async (f: File) => ({ name: f.name, data: 'AA==', mimeType: 'image/png', width: 900, height: 1200 })) }));
import App from '../src/App';
import { generateImage } from '../src/lib/gemini';
const img: ImageAsset = { name: 'test-output', data: 'AA==', mimeType: 'image/png', width: 900, height: 1200 };
beforeEach(() => {
  const values = new Map<string, string>();
  vi.stubGlobal('localStorage', { getItem: (k: string) => values.get(k) ?? null, setItem: (k: string, v: string) => values.set(k, v), removeItem: (k: string) => values.delete(k), clear: () => values.clear() });
  vi.stubGlobal('IntersectionObserver', class { callback: (entries: { isIntersecting: boolean }[]) => void; constructor(callback: (entries: { isIntersecting: boolean }[]) => void) { this.callback = callback; } observe() { this.callback([{ isIntersecting: true }]); } disconnect() {} unobserve() {} });
  vi.stubGlobal('scrollTo', vi.fn());
  vi.mocked(generateImage).mockReset().mockResolvedValue({ image: img, history: [{ role: 'model', parts: [{ inlineData: { data: 'AA==', mimeType: 'image/png' }, thoughtSignature: 'test-signature' }] }] });
});
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
it('requires two explicit approvals, then saves and restores an identity and an automatic swap', async () => {
  const view = render(<App />);
  fireEvent.change(screen.getByPlaceholderText('Enter your Google API key'), { target: { value: 'TEST_ONLY_KEY' } });
  fireEvent.click(screen.getByRole('button', { name: 'Connect & open studio' }));
  await screen.findByRole('heading', { name: 'Create identity' });
  fireEvent.change(screen.getByLabelText('Identity name'), { target: { value: 'Test identity' } });
  const file = new File(['test'], 'test.png', { type: 'image/png' });
  for (const side of ['front', 'back']) fireEvent.change(screen.getByLabelText(`Upload ${side} view`, { selector: 'input' }), { target: { files: [file] } });
  await waitFor(() => expect((screen.getByRole('button', { name: 'Generate identity' }) as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(screen.getByRole('button', { name: 'Generate identity' }));
  const prepare = await screen.findByRole('button', { name: 'Approve & prepare bases' });
  expect((prepare as HTMLButtonElement).disabled).toBe(true);
  expect(generateImage).toHaveBeenCalledTimes(2);
  fireEvent.click(screen.getByLabelText('I approve this different fictional identity and its matching front and back views.'));
  fireEvent.click(prepare);
  const save = await screen.findByRole('button', { name: 'Approve & save identity' });
  expect((save as HTMLButtonElement).disabled).toBe(true);
  expect(generateImage).toHaveBeenCalledTimes(4);
  fireEvent.click(screen.getByLabelText('I approve these bases. The model identity and pose are preserved.'));
  fireEvent.click(save);
  await screen.findByText('Identity saved', { selector: '.saved-status' });
  expect(screen.getByRole('heading', { name: 'Test identity' })).toBeTruthy();
  fireEvent.click(screen.getByRole('button', { name: 'Use in a bra swap', exact: true }));
  await screen.findByRole('heading', { name: 'Bra swap' });
  const identityPhoto = await screen.findByRole('button', { name: 'Select Test identity' });
  expect(identityPhoto.getAttribute('aria-pressed')).toBe('true');
  fireEvent.click(identityPhoto);
  expect(screen.queryByLabelText('Saved identity')).toBeNull();
  fireEvent.change(screen.getByLabelText('Bra name (optional)'), { target: { value: 'Test garment' } });
  for (const side of ['front', 'back']) fireEvent.change(screen.getByLabelText(`Upload ${side} view`, { selector: 'input' }), { target: { files: [file] } });
  await waitFor(() => expect((screen.getByRole('button', { name: 'Generate bra swap' }) as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(screen.getByRole('button', { name: 'Generate bra swap' }));
  await screen.findByText('Both views saved', { selector: '.saved-status' });
  expect(generateImage).toHaveBeenCalledTimes(6);
  expect(screen.getByRole('heading', { name: 'Test garment' })).toBeTruthy();
  view.unmount();
  render(<App />);
  await screen.findByText('Identity saved', { selector: '.saved-status' });
  fireEvent.click(screen.getByRole('tab', { name: 'Bra swap' }));
  await screen.findByText('Both views saved', { selector: '.saved-status' });
  expect(generateImage).toHaveBeenCalledTimes(6);
});
