// Run through npm run test:rules; no real account or Google generation is used.
import { readFileSync } from 'node:fs';
import { initializeTestEnvironment, assertFails, assertSucceeds, type RulesTestEnvironment } from '@firebase/rules-unit-testing';
import { doc, getDoc, getDocs, collection, setDoc, updateDoc, deleteDoc, writeBatch, type Firestore } from 'firebase/firestore';
import { ref, uploadBytes, getBytes, deleteObject } from 'firebase/storage';
import { afterAll, beforeAll, beforeEach, describe, it, expect } from 'vitest';
let env: RulesTestEnvironment;
const enabled = Boolean(process.env.FIRESTORE_EMULATOR_HOST);
const record = (uid: string, id: string, slot = 'identity-0') => ({ id, slot, state: 'saving', kind: slot.startsWith('identity') ? 'identity' : 'swap', name: 'Test model', ownerId: uid, ownerName: 'Tester', createdAt: Date.now(), model: 'gemini-3-pro-image', resolution: '2K', promptVersion: 'swap-v5-identity-framing', identityId: '', identityName: '', assets: Object.fromEntries(['front', 'back'].map(view => [view, { path: `library/${slot}/${view}`, version: id, bytes: 4, name: 'test.png', mimeType: 'image/png', width: 900, height: 1200 }])) });
function allocate(db: Firestore, data: ReturnType<typeof record>) {
  const batch = writeBatch(db);
  batch.set(doc(db, 'records', data.id), data);
  batch.set(doc(db, 'librarySlots', data.slot), { ownerId: data.ownerId, recordId: data.id, kind: data.kind });
  return batch.commit();
}
describe.skipIf(!enabled)('Firebase library capacity, deletion, and account-key rules', () => {
  beforeAll(async () => {
    env = await initializeTestEnvironment({ projectId: 'demo-swap-studio', firestore: { host: '127.0.0.1', port: 8080, rules: readFileSync('firebase/firestore.rules', 'utf8') }, storage: { host: '127.0.0.1', port: 9199, rules: readFileSync('firebase/storage.rules', 'utf8') } });
  });
  beforeEach(async () => { await env.clearFirestore(); await env.clearStorage(); });
  afterAll(async () => { await env?.cleanup(); });
  it('requires an atomic bounded reservation, shares reads, and forbids overwrites and extra assets', async () => {
    const alice = env.authenticatedContext('alice').firestore();
    const bob = env.authenticatedContext('bob').firestore();
    await assertFails(setDoc(doc(alice, 'records', 'unreserved'), record('alice', 'unreserved')));
    await assertSucceeds(allocate(alice, record('alice', 'a')));
    await assertSucceeds(getDoc(doc(bob, 'records', 'a')));
    await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(), 'records', 'a')));
    await assertFails(allocate(bob, record('bob', 'b')));
    await assertFails(allocate(alice, record('alice', 'over-limit', 'identity-20')));
    const extras = record('alice', 'extras', 'identity-1'); extras.assets.referenceFront = extras.assets.front;
    await assertFails(allocate(alice, extras));
    await assertFails(allocate(alice, { ...record('alice', 'bad', 'identity-1'), ownerId: 'bob' }));
    const large = record('alice', 'large', 'identity-1'); large.assets.front.bytes = 16 * 1024 * 1024 + 1;
    await assertFails(allocate(alice, large));
    const path = record('alice', 'bad-path', 'identity-1'); path.assets.front.path = 'library/identity-0/front';
    await assertFails(allocate(alice, path));
    await assertSucceeds(updateDoc(doc(alice, 'records', 'a'), { state: 'ready' }));
    await assertFails(updateDoc(doc(alice, 'records', 'a'), { state: 'saving' }));
  });
  it('enforces 20 identity slots across accounts, including simultaneous claims', async () => {
    const alice = env.authenticatedContext('alice').firestore();
    const bob = env.authenticatedContext('bob').firestore();
    const claims = await Promise.allSettled([allocate(alice, record('alice', 'race-a')), allocate(bob, record('bob', 'race-b'))]);
    expect(claims.filter(r => r.status === 'fulfilled')).toHaveLength(1);
    for (let i = 1; i < 20; i++) await assertSucceeds(allocate(alice, record('alice', `model-${i}`, `identity-${i}`)));
    await assertFails(allocate(bob, record('bob', 'model-21', 'identity-20')));
    await assertFails(allocate(bob, record('bob', 'collision', 'identity-19')));
  });
  it('saves swaps with only final views, preserves dimension checks, and rejects slot 101', async () => {
    const alice = env.authenticatedContext('alice').firestore();
    await allocate(alice, record('alice', 'identity'));
    await updateDoc(doc(alice, 'records', 'identity'), { state: 'ready' });
    const swap = { ...record('alice', 'swap', 'swap-99'), identityId: 'identity' };
    swap.assets.front.width = 2816;
    await assertFails(allocate(alice, swap));
    swap.assets.front.width = 900;
    await assertSucceeds(allocate(alice, swap));
    await assertFails(allocate(alice, { ...record('alice', 'over', 'swap-100'), identityId: 'identity' }));
  });
  it('deletes owned images, blocks other members, and frees a slot only in the deletion transaction', async () => {
    const aliceContext = env.authenticatedContext('alice');
    const db = aliceContext.firestore(); const storage = aliceContext.storage();
    const bob = env.authenticatedContext('bob');
    await allocate(db, record('alice', 'a'));
    const imageRef = ref(storage, 'library/identity-0/front');
    const bytes = new Uint8Array([137, 80, 78, 71]);
    const meta = { contentType: 'image/png', customMetadata: { recordId: 'a' } };
    await assertSucceeds(uploadBytes(imageRef, bytes, meta));
    await assertFails(uploadBytes(ref(storage, 'library/identity-0/referenceFront'), bytes, meta));
    await assertFails(uploadBytes(ref(storage, 'library/identity-1/front'), bytes, meta));
    await assertFails(uploadBytes(ref(storage, 'users/alice/a/front'), bytes, meta));
    await assertFails(uploadBytes(ref(storage, 'library/identity-0/back'), new Uint8Array(5), meta));
    await assertFails(uploadBytes(ref(bob.storage(), 'library/identity-0/back'), bytes, meta));
    await assertSucceeds(updateDoc(doc(db, 'records', 'a'), { state: 'ready' }));
    await assertSucceeds(getBytes(ref(bob.storage(), 'library/identity-0/front')));
    await assertFails(getBytes(ref(env.unauthenticatedContext().storage(), 'library/identity-0/front')));
    await assertFails(uploadBytes(imageRef, bytes, meta));
    await assertFails(deleteObject(imageRef));
    await assertFails(updateDoc(doc(bob.firestore(), 'records', 'a'), { state: 'deleting' }));
    await assertSucceeds(updateDoc(doc(db, 'records', 'a'), { state: 'deleting' }));
    await assertFails(deleteObject(ref(bob.storage(), 'library/identity-0/front')));
    await assertSucceeds(deleteObject(imageRef));
    await assertFails(deleteDoc(doc(db, 'records', 'a')));
    await assertFails(deleteDoc(doc(db, 'librarySlots', 'identity-0')));
    const batch = writeBatch(db); batch.delete(doc(db, 'records', 'a')); batch.delete(doc(db, 'librarySlots', 'identity-0'));
    await assertSucceeds(batch.commit());
    await assertSucceeds(allocate(bob.firestore(), record('bob', 'new-occupant')));
    await assertFails(uploadBytes(imageRef, bytes, meta));
  });
  it('keeps account keys private even from other members and disallows collection listing', async () => {
    const alice = env.authenticatedContext('alice').firestore();
    const bob = env.authenticatedContext('bob').firestore();
    const keyRef = doc(alice, 'privateKeys', 'alice');
    await assertSucceeds(setDoc(keyRef, { key: 'TEST_ONLY_FAKE_KEY', updatedAt: Date.now() }));
    await assertSucceeds(getDoc(keyRef));
    await assertFails(getDoc(doc(bob, 'privateKeys', 'alice')));
    await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(), 'privateKeys', 'alice')));
    await assertFails(getDocs(collection(alice, 'privateKeys')));
    await assertFails(setDoc(doc(bob, 'privateKeys', 'alice'), { key: 'TEST_ONLY_FAKE_KEY', updatedAt: Date.now() }));
    await assertFails(deleteDoc(doc(bob, 'privateKeys', 'alice')));
    await assertSucceeds(deleteDoc(keyRef));
    await assertFails(setDoc(doc(alice, 'users', 'alice'), { password: 'not-allowed' }));
  });
  it('bounds private preview files and deletes them with the original pair', async () => {
    const alice = env.authenticatedContext('alice'); const bob = env.authenticatedContext('bob');
    const data = record('alice', 'preview');
    const thumbnail = { ...data.assets.front, path: 'library/identity-0/front-thumb', width: 360, height: 480, mimeType: 'image/jpeg' };
    Object.assign(data.assets.front, { thumbnail });
    thumbnail.bytes = 128 * 1024 + 1;
    await assertFails(allocate(alice.firestore(), data));
    thumbnail.bytes = 4; thumbnail.width = 481;
    await assertFails(allocate(alice.firestore(), data));
    thumbnail.width = 360; thumbnail.path = 'library/identity-0/extra-thumb';
    await assertFails(allocate(alice.firestore(), data));
    thumbnail.path = 'library/identity-0/front-thumb';
    await assertSucceeds(allocate(alice.firestore(), data));
    const path = ref(alice.storage(), thumbnail.path); const bytes = new Uint8Array(4);
    const metadata = { contentType: 'image/jpeg', customMetadata: { recordId: data.id } };
    await assertSucceeds(uploadBytes(path, bytes, metadata));
    await assertFails(uploadBytes(path, new Uint8Array(128 * 1024 + 1), metadata));
    await assertFails(uploadBytes(path, bytes, { ...metadata, contentType: 'image/png' }));
    await assertFails(uploadBytes(ref(alice.storage(), 'library/identity-0/back-thumb'), bytes, metadata));
    await assertFails(uploadBytes(ref(bob.storage(), thumbnail.path), bytes, metadata));
    await assertSucceeds(getBytes(ref(bob.storage(), thumbnail.path)));
    await assertFails(getBytes(ref(env.unauthenticatedContext().storage(), thumbnail.path)));
    await assertSucceeds(updateDoc(doc(alice.firestore(), 'records', data.id), { state: 'ready' }));
    await assertFails(uploadBytes(path, bytes, metadata));
    await assertFails(deleteObject(path));
    await assertSucceeds(updateDoc(doc(alice.firestore(), 'records', data.id), { state: 'deleting' }));
    await assertFails(deleteObject(ref(bob.storage(), thumbnail.path)));
    await assertSucceeds(deleteObject(path));
  });
});
